name: Deploy to Pterodactyl

on:
  push:
    branches:
      - main # Sesuaikan ke master jika branch Anda menggunakan nama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pterodactyl Deploy
        uses: Avenze/pterodactyl-actions@v1.0.3
        with:
          panel-url: 'https://serverku.lynzzofficial.com/server/0263f22b' # ⚠️ Ganti dengan URL panel Pterodactyl Anda
          api-key: ${{ secrets.PTERODACTYL_API_KEY }}
          server-id: ${{ secrets.PTERODACTYL_SERVER_ID }}
