name: Deploy to Pterodactyl SFTP

on:
  push:
    branches:
      - main # Sesuaikan menjadi master jika branch utama Anda bernama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SFTP Deploy to Pterodactyl
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'kuinzee.0263f22b'        # ⚠️ GANTI dengan Username SFTP dari panel Pterodactyl Anda
          server: '://ndserverku.lynzzofficial.com'          # ⚠️ GANTI dengan IP / Host SFTP Pterodactyl Anda (tanpa sftp:// dan tanpa :2022)
          port: 2022                        # Port SFTP Pterodactyl
          password: ${{ secrets.PTERO_PASSWORD }}
          local_path: './*'                 # Mengambil semua file di repository
          remote_path: '/'                  # Dimasukkan ke direktori utama server Pterodactyl
          sftp_only: true
