name: Deploy to Pterodactyl SFTP

on:
  push:
    branches:
      - main # Sesuaikan menjadi master jika branch Anda master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SFTP Deploy to Pterodactyl
        uses: SamKirkland/SFTP-Deploy-Action@v4.3.5
        with:
          server: '://ndserverku.lynzzofficial.com'          # ⚠️ GANTI dengan alamat IP / Host SFTP Pterodactyl Anda (tanpa sftp:// dan tanpa :2022)
          port: 2022                        # ⚠️ Port default SFTP Pterodactyl biasanya 2022
          username: 'kuinzee.0263f22b'        # ⚠️ GANTI dengan Username SFTP dari panel Pterodactyl Anda
          password: ${{ secrets.PTERO_PASSWORD }}
          protocol: sftp
          local-dir: './'                   # Mengirim semua file dari GitHub
          server-dir: '/'                   # Dimasukkan ke folder utama Pterodactyl
